server:
  port: 8081

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://localhost:5433/bootcamp_db
    username: postgres
    password: postgres!
    driverClassName: org.postgresql.Driver

  sql:
    init:
      platform: postgres

  graphql:
    graphiql:
      enabled: true
    path: /graphql
    schema:
      printer:
        enabled: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9093}
    topic:
      entrance-exit-events-topic: entrance-exit-events
      event-logs-topic: event-logs
    consumer:
      group-id:
        entrance-exit-events-consumer: entrance-exit-events-consumer
        event-logs-consumer: event-logs-consumer
